In [1]:
import pandas as pd

In [2]:
data =pd.read_excel("/my data.xlsx")

In [3]:
data.head()

,Patient_ID,Visit_Date,Gender,Age,Department,Diagnosis_Category,Bill_Amount
0,PAT00160,2025-08-06,Female,74,NaN,Routine Checkup,252.79
1,PAT00156,2025-12-30,Male,5,Maternity,Cardiovascular,189.10
2,PAT00188,2025-11-10,NaN,68,Emergency,Routine Checkup,126.17
3,PAT00073,2025-10-02,Male,82,Outpatient,Infection,44.56
4,PAT00199,2026-05-21,Female,46,Pediatrics,Maternal,74.29

In [4]:
data.rename(columns={"Bill_Amount": "Amount"}, inplace=True)

In [5]:
data.head()

  Patient_ID Visit_Date  Gender Age  Department Diagnosis_Category  Amount
0   PAT00160 2025-08-06  Female  74         NaN    Routine Checkup  252.79
1   PAT00156 2025-12-30    Male   5   Maternity     Cardiovascular  189.10
2   PAT00188 2025-11-10     NaN  68   Emergency    Routine Checkup  126.17
3   PAT00073 2025-10-02    Male  82  Outpatient          Infection   44.56
4   PAT00199 2026-05-21  Female  46  Pediatrics           Maternal   74.29

In [6]:
data.drop(columns=["Gender"])

    Patient_ID Visit_Date Age         Department Diagnosis_Category  Amount
0     PAT00160 2025-08-06  74                NaN    Routine Checkup  252.79
1     PAT00156 2025-12-30   5          Maternity     Cardiovascular  189.10
2     PAT00188 2025-11-10  68          Emergency    Routine Checkup  126.17
3     PAT00073 2025-10-02  82         Outpatient          Infection   44.56
4     PAT00199 2026-05-21  46         Pediatrics           Maternal   74.29
..         ...        ...  ..                ...                ...     ...
295   PAT00200 2025-09-27  84  Internal Medicine    Routine Checkup  238.03
296   PAT00169 2025-12-23  13          Emergency     Cardiovascular  119.04
297   PAT00221 2026-04-06  25         Outpatient    Routine Checkup   66.20
298   PAT00084 2025-05-15  61          Emergency    routine checkup  117.85
299   PAT00110        NaT  79         Outpatient    Routine Checkup   83.84

[300 rows x 6 columns]

In [7]:
data.head()

  Patient_ID Visit_Date  Gender Age  Department Diagnosis_Category  Amount
0   PAT00160 2025-08-06  Female  74         NaN    Routine Checkup  252.79
1   PAT00156 2025-12-30    Male   5   Maternity     Cardiovascular  189.10
2   PAT00188 2025-11-10     NaN  68   Emergency    Routine Checkup  126.17
3   PAT00073 2025-10-02    Male  82  Outpatient          Infection   44.56
4   PAT00199 2026-05-21  Female  46  Pediatrics           Maternal   74.29